version: "2.24"

services:
  zookeeper:
   image: bitnami/zookeeper:latest
   container_name: zookeeper
   volumes:
    - zookeeper-vol:/bitnami/zookeeper
   ports:
    - "2181:2181"
   environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  
   networks: 
    - kafka-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - '9092:9092'
    volumes:
      - zookeeper-vol:/bitnami/zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks: 
      - kafka-network
    depends_on:
      - zookeeper
volumes:
  zookeeper-vol:
    external: true
  kafka-vol:
    external: true
networks:
  kafka-network: